// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTiy24jzZZ04EyyhAGXtl6x8p4lW6-X0',
    appId: '1:768490035747:web:1f16342cacae31ac0eaf96',
    messagingSenderId: '768490035747',
    projectId: 'interiorx-3c5a6',
    authDomain: 'interiorx-3c5a6.firebaseapp.com',
    storageBucket: 'interiorx-3c5a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAvqxcZQEoSlTieOmTr5-mLjmU2c6o20',
    appId: '1:768490035747:android:cf70a03a374b8b6a0eaf96',
    messagingSenderId: '768490035747',
    projectId: 'interiorx-3c5a6',
    storageBucket: 'interiorx-3c5a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9M_cikQwRGs6k0hjSPpamJy9-ETEDwNs',
    appId: '1:768490035747:ios:7e6cbcb95a8964d70eaf96',
    messagingSenderId: '768490035747',
    projectId: 'interiorx-3c5a6',
    storageBucket: 'interiorx-3c5a6.appspot.com',
    iosBundleId: 'com.example.interiorx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9M_cikQwRGs6k0hjSPpamJy9-ETEDwNs',
    appId: '1:768490035747:ios:7e6cbcb95a8964d70eaf96',
    messagingSenderId: '768490035747',
    projectId: 'interiorx-3c5a6',
    storageBucket: 'interiorx-3c5a6.appspot.com',
    iosBundleId: 'com.example.interiorx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJTiy24jzZZ04EyyhAGXtl6x8p4lW6-X0',
    appId: '1:768490035747:web:7b23e6bdec58fae70eaf96',
    messagingSenderId: '768490035747',
    projectId: 'interiorx-3c5a6',
    authDomain: 'interiorx-3c5a6.firebaseapp.com',
    storageBucket: 'interiorx-3c5a6.appspot.com',
  );
}
